export default [
  'Aarüti',
  'Albispasshöhe',
  'Albisrieden',
  'Albisriederdörfli',
  'Albisriederplatz',
  'Allenberg',
  'Alter Bahnhof',
  'Altes Schulhaus',
  'Altmoos',
  'Am Rietpark',
  'Am Wildbach',
  'Appital',
  'Asylstrasse',
  'Austrasse',
  'Auzelg Ost',
  'Bachstrasse',
  'Bad',
  'Bad Kämmoos',
  'Bahnhof Altstetten',
  'Bahnhof Altstetten Nord',
  'Bahnhof Enge',
  'Bahnhof Enge/Bederstr.',
  'Bahnhof Hardbrücke',
  'Bahnhof Hegi',
  'Bahnhof Oerlikon Nord',
  'Bahnhof Oerlikon Ost',
  'Bahnhof Ost',
  'Bahnhof SOB',
  'Bahnhof Stettbach',
  'Bahnhof Süd',
  'Bahnhof Wiedikon',
  'Bahnhof Wipkingen',
  'Bahnhof Wollishofen',
  'Bahnhof Wülflingen',
  'Bahnhofquai/HB',
  'Bahnhofstrasse',
  'Bahnübergang',
  'Zürich 110',
  'Bandwies',
  'Bassersdorf',
  'Beerimoos',
  'Belsito',
  'Bergheim',
  'Bergstrasse',
  'Bernold',
  'Bertastrasse',
  'Bertschikon bei Attikon',
  'Besenrainstrasse',
  'Bettenplatz',
  'Bezirksschule',
  'Bhf.Wollishofen/Staubstr.',
  'Binz',
  'Binz Center',
  'Binzackerstrasse',
  'Birchdörfli',
  'Bircher-Benner',
  'Birchstrasse',
  'Birchwil bei Nürensdorf',
  'Blitzgbach',
  'Blumenweg',
  'Bodenacher',
  'Bollwies',
  'Bramen',
  'Branzenäsch',
  'Brücke',
  'Brunaustrasse',
  'Brünigstrasse',
  'Büchel',
  'Buchs-Dällikon',
  'Bülach',
  'Bürkliplatz',
  'Burstel',
  'Ceder',
  'Central Polybahn',
  'Chalchofen',
  'Chammerholzstr.',
  'Chis/Naturstation',
  'Dangelstrasse',
  'Dänikon',
  'Dorfmitti',
  'Dreiwiesen',
  'Driesbüel',
  'Dübendorf',
  'Dünni',
  'Einkaufszentrum Süd',
  'Elgg',
  'EPI-Klinik',
  'Erlen',
  'Escher-Wyss-Platz',
  'Eschikon',
  'ETH/Universitätsspital',
  'Ettenfeld',
  'Farnboden',
  'Feldhof',
  'Felsenegg',
  'Felsenstrasse',
  'Fernsicht',
  'Finken-Rain',
  'Fistel',
  'Florastrasse',
  'Föhrenstrasse',
  'Forschungsanstalt',
  'Freckmünd',
  'Freihof',
  'Freizeitanlage',
  'Friedenstrasse',
  'Friedhof Enzenbühl',
  'Friedhof Federen',
  'Friedhof Schwandenholz',
  'Friedhof Sihlfeld',
  'Friedhof Uetliberg',
  'Friedhof Witikon',
  'Friedliweg',
  'Friesenberg',
  'Friesenberghalde',
  'Friesenbergstrasse',
  'Frohberg',
  'Frohheimstrasse',
  'Frohmatt',
  'Frowiesstrasse',
  'Fuchshalde',
  'Gerenhalde',
  'Gessnerstrasse',
  'Gibswil',
  'Glaubtenstrasse',
  'Glaubtenstrasse Nord',
  'Glaubtenstrasse Süd',
  'Glockenacker',
  'Goldackerweg',
  'Goldauerstrasse',
  'Goldbacherstrasse',
  'Goldhaldenplatz',
  'Grindel',
  'Grueb',
  'Grund',
  'Grüt',
  'Gütighausen',
  'Guyer-Weg',
  'Hadlikon',
  'Hagenstal',
  'Haldenbrücke',
  'Haldengut',
  'Hallenbad/Frohmatt',
  'Hardhölzli',
  'Hardturm',
  'Harossen',
  'Hedy Hahnloser',
  'Hegetsberg',
  'Hegibachplatz',
  'Hegifeld',
  'Heligenmattstrasse',
  'Helvetiaplatz',
  'Henggart',
  'Herdernstrasse',
  'Herdlen',
  'Herracher',
  'Herti',
  'Hesligenstrasse',
  'Heuelstrasse',
  'Heuwinkelstrasse',
  'Hinentalstrasse',
  'Hinterbirch',
  'Hirslen',
  'Hittenberg',
  'Hofmatt',
  'Hofwiesen',
  'Höhestrasse',
  'Hölderlinstrasse',
  'Holenbach',
  'Holzhusen',
  'Horben',
  'Hotel Panorama',
  'Hubertus',
  'Hubstrasse',
  'Humbel',
  'Hünikon (Neftenbach)',
  'Hürstholz',
  'Hüttenstrasse',
  'Im Feld',
  'Im Hagacker',
  'Im Haufland',
  'Im Klösterli',
  'Im Langacher',
  'In der Au',
  'In der Höh',
  'Juckeren',
  'Jungholz',
  'Kalkbreite/Bhf.Wiedikon',
  'Kämmaten',
  'Kantonalbank',
  'Kantonsschule',
  'Kantonsschulen',
  'Kappeli',
  'Käppeli',
  'Käserei',
  'Kastellstrasse',
  'Kempraten',
  'Kesslerstrasse',
  'Kilchberg',
  'Kirche',
  'Kirche Wetzwil',
  'Kloster',
  'Kniebreche',
  'Krähbach',
  'Kreuz',
  'Kreuzstrasse',
  'Krone',
  'Kronenweg',
  'Kunsteisbahn',
  'Küsnacht Goldbach',
  'Landhus',
  'Landolt-Junker-Str.',
  'Langfuren',
  'Langhag',
  'Langmoos',
  'Laubisrüti',
  'Laufenbach',
  'Leimgrübelstrasse',
  'Leingrüebler',
  'Lerchenrain',
  'Lerzen',
  'Letzibach',
  'Letzigrund',
  'Letzipark',
  'Letzipark West',
  'Letzistrasse',
  'Leuen',
  'Lieburg',
  'Lindauerstrasse',
  'Lindenstrasse',
  'Lochhof',
  'Loomatt',
  'Loorstrasse',
  'Luberzen',
  'Luegeten',
  'Luppmen',
  'Maillartstrasse',
  'Manegg',
  'Manesseplatz',
  'Männedorf',
  'Marmori-Weiher',
  'Maur (See)',
  'Medikon',
  'Meierhof-Rain',
  'Mettlenstrasse',
  'Michelstrasse',
  'Mies',
  'Milchhütte',
  'Mittelalbis',
  'Mode Center TMC',
  'Morgenthal',
  'Mühle',
  'Museum Rietberg',
  'Museumstrasse/HB',
  'Neuaffoltern',
  'Neu-Bachs',
  'Neudorf',
  'Neumatt',
  'Neuthal bei Bäretswil',
  'Nordstrasse',
  'Nöschikon',
  'Nürensdorferstrasse',
  'Oberwil',
  'Oerlingen',
  'OPC',
  'Opfikon',
  'Ormis',
  'Ottikon b. Kemptthal',
  'Paradies',
  'Pflegezentrum',
  'Platten',
  'Poststrasse',
  'Psych. Uniklinik',
  'Querstrasse',
  'Radmühle',
  'Rafz',
  'Raubbühl',
  'Rautistrasse',
  'Rebackerweg',
  'Rebbergstrasse',
  'Regensdorf-Watt',
  'Rehazentrum',
  'Rentenanstalt',
  'Reppischhof',
  'Riedenerstrasse',
  'Riedhof',
  'Riedmatt',
  'Rigistrasse',
  'Römertor',
  'Roos',
  'Röslistrasse',
  'Rossau',
  'Rotbuchstrasse',
  'Rote Fabrik',
  'Rotflue',
  'Ruetschbergstr.',
  'Rütistrasse',
  'Saatlenstrasse',
  'Sackzelg',
  'Sädlenweg',
  'Sagenbach',
  'Salzweg',
  'Samstagern',
  'Schäflibach',
  'Schäppiweg',
  'Schärbächli/Fähre',
  'Schaufelbergerstrasse',
  'Scheidegg',
  'Scheuren',
  'Schiffst.',
  'Schmidgasse',
  'Schmiedstube',
  'Schönenwerd',
  'Schornäglen',
  'Schulhaus Buchlern',
  'Schulhaus Bürgli',
  'Schürgistrasse',
  'Schürli',
  'Schwandenholz',
  'Schwandweg',
  'Schweizäcker',
  'Schweizerhof',
  'Schwerzenbach ZH',
  'Seebacherplatz',
  'Seestrasse',
  'Segel',
  'Seidelhof',
  'Seilbahn Rigiblick',
  'Seitenacker',
  'Signaustrasse',
  'Sihlau',
  'Sihlcity Nord',
  'Sihlegg',
  'Sihlquai/HB',
  'Sihlstrasse',
  'Sihlwald',
  'Silbern',
  'Soliboden',
  'Soligänter',
  'Sonnenberg',
  'Sportzentrum',
  'Spyriplatz',
  'Spyristeig',
  'St. Dionys',
  'Stadthalle',
  'Stapferstrasse',
  'Stauffacher',
  'Stedtli',
  'Sternen/WSL',
  'Stierwisen',
  'Stoffelstrasse',
  'Strick',
  'Strickler',
  'Sulzbach',
  'Swica',
  'Tänler',
  'Technorama',
  'Tiefacker',
  'Titlisstrasse',
  'Tobel',
  'Töbeli',
  'Tolhusen',
  'Töss',
  'Trichtenhauserm.',
  'Triemli',
  'Triemlispital',
  'Trotte',
  'Tüfi',
  'Tumigerstrasse',
  'Turbenthal',
  'Uitikon Waldegg',
  'Unter Ort',
  'Unteralbis',
  'Unterottikon',
  'Viadukt',
  'Vogtei',
  'Vontobel',
  'Waffenplatzstrasse',
  'Wageren',
  'Waidfussweg',
  'Waidhof',
  'Waidli',
  'Waisenhausstrasse',
  'Waldhaus Dolder',
  'Waldheim',
  'Wasen',
  'Wasserfuri',
  'Weiherstrasse',
  'Werdhölzli',
  'Werft',
  'Wetzikon ZH',
  'Widum',
  'Wiesliacher',
  'Wigarten',
  'Wildpark-Höfli',
  'Winterberg',
  'Winzerstrasse',
  'Winzerstrasse Süd',
  'Wipkingerplatz',
  'Wisental',
  'Witzberg',
  'Wonnebergstrasse',
  'Wright-Strasse',
  'Würzhalde',
  'Zehntenstrasse',
  'Zoo/Forrenweid',
  'Zopf',
  'Zürichstrasse',
  'Zweidlen',
  'Zwinggarten',
  'Zypressenstrasse'
]
