export default [
  'Aargauerstrasse',
  'Albisgütli',
  'Albisrank',
  'Albisrieden',
  'Albisriederdörfli',
  'Albisriederplatz',
  'Alte Trotte',
  'Altenhofstrasse',
  'Altes Krematorium',
  'Althoos',
  'Altried',
  'Am Börtli',
  'Am Suteracher',
  'Appenzellerstrasse',
  'Aspholz',
  'Aubrücke',
  'Ausserdorfstrasse',
  'Auzelg',
  'Auzelg Ost',
  'Bachmattstrasse',
  'Bäckeranlage',
  'Bad Allenmoos',
  'Bahnhof Affoltern',
  'Bahnhof Altstetten',
  'Bahnhof Altstetten Nord',
  'Bahnhof Enge',
  'Bahnhof Enge/Bederstr.',
  'Bahnhof Hardbrücke',
  'Bahnhof Leimbach',
  'Bahnhof Oerlikon',
  'Bahnhof Oerlikon Nord',
  'Bahnhof Oerlikon Ost',
  'Bahnhof Selnau',
  'Bahnhof Stadelhofen',
  'Bahnhof Stettbach',
  'Bahnhof Tiefenbrunnen',
  'Bahnhof Wiedikon',
  'Bahnhof Wipkingen',
  'Bahnhof Wollishofen',
  'Bahnhofplatz/HB',
  'Bahnhofquai/HB',
  'Bahnhofstrasse/HB',
  'Balgrist',
  'Bändliweg',
  'Baslerstrasse',
  'Beckenhof',
  'Bellevue',
  'Berghaldenstrasse',
  'Bergstation Dolderbahn',
  'Berninaplatz',
  'Bernoulli-Häuser',
  'Bertastrasse',
  'Berufswahlschule',
  'Besenrainstrasse',
  'Bethanien',
  'Bezirksgebäude',
  'Bhf. Wollishofen/Werft',
  'Bhf.Wollishofen/Staubstr.',
  'Billoweg',
  'Binz',
  'Binz Center',
  'Birch-/Glatttalstrasse',
  'Birchdörfli',
  'Bircher-Benner',
  'Birchstrasse',
  'Bleulerstrasse',
  'Blumenfeldstrasse',
  'Bocklerstrasse',
  'Bollingerweg',
  'Botanischer Garten',
  'Brandschenkestrasse',
  'Bristenstrasse',
  'Brunau/Mutschellenstr.',
  'Brunaustrasse',
  'Bucheggplatz',
  'Buchholz',
  'Buhnstrasse',
  'Burgwies',
  'Bürkliplatz',
  'Butzenstrasse',
  'Carl-Spitteler-Strasse',
  'Central',
  'Central Polybahn',
  'Chaletweg',
  'Chinagarten',
  'Dammweg',
  'Dangelstrasse',
  'Dorflinde',
  'Dreispitz',
  'Dreiwiesen',
  'Drusbergstrasse',
  'Dunkelhölzli',
  'Einfangstrasse',
  'Elektrowatt',
  'Englischviertelstrasse',
  'EPI-Klinik',
  'Eschergutweg',
  'Escher-Wyss-Platz',
  'ETH Hönggerberg',
  'ETH/Universitätsspital',
  'Ettenfeld',
  'Farbhof',
  'Feldeggstrasse',
  'Fellenbergstrasse',
  'Felsenrainstrasse',
  'Fernsehstudio',
  'Feusisbergli',
  'Fischerweg',
  'Flobotstrasse',
  'Flühgasse',
  'Flurstrasse',
  'Förrlibuckstrasse',
  'Frankental',
  'Freiestrasse',
  'Freihofstrasse',
  'Friedackerstrasse',
  'Friedhof Eichbühl',
  'Friedhof Enzenbühl',
  'Friedhof Hönggerberg',
  'Friedhof Schwandenholz',
  'Friedhof Sihlfeld',
  'Friedhof Uetliberg',
  'Friedhof Witikon',
  'Friedrichstrasse',
  'Friesenberg',
  'Friesenberghalde',
  'Friesenbergstrasse',
  'Frohburg',
  'Fröhlichstrasse',
  'Fronwald',
  'Frymannstrasse',
  'Geeringstrasse',
  'Genossenschaftsstrasse',
  'Germaniastrasse',
  'Giblenstrasse',
  'Glatt',
  'Glattpark',
  'Glattwiesen',
  'Glaubtenstrasse',
  'Glaubtenstrasse Nord',
  'Glaubtenstrasse Süd',
  'Glockenacker',
  'Goldackerweg',
  'Goldauerstrasse',
  'Goldbrunnenplatz',
  'Grimselstrasse',
  'Grubenstrasse',
  'Grünaustrasse',
  'Grünwald',
  'Guggachstrasse',
  'Güterbahnhof',
  'Gutstrasse',
  'Hadlaubstrasse',
  'Hagenholz',
  'Haldenbach',
  'Haldenegg',
  'Hallenbad Oerlikon',
  'Hardhof',
  'Hardplatz',
  'Hardturm',
  'Hedwigsteig',
  'Heerenwiesen',
  'Hegianwandweg',
  'Hegibachplatz',
  'Heizenholz',
  'Helmhaus',
  'Helvetiaplatz',
  'Herbstweg',
  'Herdernstrasse',
  'Hermetschloo',
  'Hertensteinstrasse',
  'Herzogenmühlestrasse',
  'Heubeeriweg',
  'Heuried',
  'Himmeri',
  'Hinterbergstrasse',
  'Hirschwiesenstrasse',
  'Hirzenbach',
  'Höfliweg',
  'Hofstrasse',
  'Hohenklingensteig',
  'Hölderlinsteig',
  'Hölderlinstrasse',
  'Holzerhurd',
  'Hönggerberg',
  'Höschgasse',
  'Hottingerplatz',
  'Hubertus',
  'Hügelstrasse',
  'Hungerbergstrasse',
  'Hürlimannplatz',
  'Hürstholz',
  'Im Ebnet',
  'Im Gut',
  'Im Hagacker',
  'Im Hüsli',
  'Im Klösterli',
  'Im Walder',
  'Im Wingert',
  'In der Ey',
  'Juchhof',
  'Jugendherberge',
  'Kalchbühlweg',
  'Kalkbreite/Bhf.Wiedikon',
  'Kanonengasse',
  'Kantonalbank',
  'Kantonsschule',
  'Kapfstrasse',
  'Kappeli',
  'Kappenbühlweg',
  'Käshaldenstrasse',
  'Kempfhofsteig',
  'Kernstrasse',
  'Kienastenwies',
  'Kinkelstrasse',
  'Kirche Fluntern',
  'Klosbach',
  'Klusplatz',
  'Köschenrüti',
  'Krematorium Nordheim',
  'Kreuzplatz',
  'Kreuzstrasse',
  'Kronenstrasse',
  'Krönleinstrasse',
  'Kunsthaus',
  'Lägernstrasse',
  'Landiwiese',
  'Langensteinenstrasse',
  'Langgrütstrasse',
  'Langmauerstrasse',
  'Laubegg',
  'Laubiweg',
  'Lehenstrasse',
  'Leimgrübelstrasse',
  'Lerchenhalde',
  'Lerchenrain',
  'Lettenstrasse',
  'Letzibach',
  'Letzigrund',
  'Letzipark',
  'Letzipark West',
  'Letzistrasse',
  'Leutschenbach',
  'Limmatplatz',
  'Lindenplatz',
  'Lochergut',
  'Loogarten',
  'Loorenstrasse',
  'Löwenplatz',
  'Luchswiesen',
  'Luegisland',
  'Maienweg',
  'Maillartstrasse',
  'Manegg',
  'Manesseplatz',
  'Marbachweg',
  'Mattenhof',
  'Max-Bill-Platz',
  'Meierhofplatz',
  'Messe/Hallenstadion',
  'Micafil',
  'Michelstrasse',
  'Milchbuck',
  'Militär-/Langstrasse',
  'Mittelleimbach',
  'Morgental',
  'Mötteliweg',
  'Mühlacker',
  'Museum für Gestaltung',
  'Museum Rietberg',
  'Neeserweg',
  'Neuaffoltern',
  'Neubühl',
  'Neumarkt',
  'Neunbrunnen',
  'Nordheimstrasse',
  'Nordstrasse',
  'Nürenbergstrasse',
  'Oberwiesenstrasse',
  'Oerlikerhus',
  'Okenstrasse',
  'Opernhaus',
  'Orionstrasse',
  'Ottikerstrasse',
  'Paradeplatz',
  'Pflegezentr. Käferberg',
  'Platte',
  'Polyterrasse ETH',
  'Post Wollishofen',
  'Probstei',
  'Quellenstrasse',
  'Radiostudio',
  'Räffelstrasse',
  'Rathaus',
  'Rautihalde',
  'Rautistrasse',
  'Rebbergsteig',
  'Regensbergbrücke',
  'Rehalp',
  'Rennweg',
  'Rentenanstalt',
  'Riedbach',
  'Riedgraben',
  'Riedhofstrasse',
  'Rigiblick',
  'Römerhof',
  'Röntgenstrasse',
  'Rosengartenstrasse',
  'Röslistrasse',
  'Roswiesen',
  'Rotbuchstrasse',
  'Rote Fabrik',
  'Rudolf-Brun-Brücke',
  'Rütihof',
  'Saalsporthalle',
  'Saatlenstrasse',
  'Sackzelg',
  'Sädlenweg',
  'Salersteig',
  'Salzweg',
  'SBB-Werkstätte',
  'Schaffhauserplatz',
  'Schanzackerstrasse',
  'Schäppiweg',
  'Schauenberg',
  'Schaufelbergerstrasse',
  'Scheuchzerstrasse',
  'Schiffbau',
  'Schiffstation',
  'Schiffstation',
  'Schiffstation',
  'Schiffstation',
  'Schiffstation',
  'Schiffstation',
  'Schiffstation',
  'Schlyfi',
  'Schmiede Wiedikon',
  'Schönauring',
  'Schörlistrasse',
  'Schulhaus Altweg',
  'Schulhaus Buchlern',
  'Schumacherweg',
  'Schürgistrasse',
  'Schützenhaus Höngg',
  'Schwamendingerplatz',
  'Schwandenholz',
  'Schweighof',
  'Schweizer Rück',
  'Schwert',
  'Seebach',
  'Seebacherplatz',
  'Seerose',
  'Segantinistrasse',
  'Segeten',
  'Seidelhof',
  'Seilbahn Rigiblick',
  'Siemens',
  'Signaustrasse',
  'Sihlcity',
  'Sihlcity Nord',
  'Sihlpost / HB',
  'Sihlquai/HB',
  'Sihlstrasse',
  'Sihlweidstrasse',
  'Singlistrasse',
  'Solidapark',
  'Sonneggstrasse',
  'Sportweg',
  'Sprecherstrasse',
  'Spyriplatz',
  'Spyristeig',
  'Stadtgrenze',
  'Stampfenbachplatz',
  'Staudenbühl',
  'Stauffacher',
  'Sternen Oerlikon',
  'Stettbach',
  'Stierenried',
  'Stockerstrasse',
  'Stodolastrasse',
  'Strassenverkehrsamt',
  'Strickhof',
  'Sukkulentensammlung',
  'Sunnau',
  'Susenbergstrasse',
  'Talwiesenstrasse',
  'Technopark',
  'Thujastrasse',
  'Tierspital',
  'Titlisstrasse',
  'Tobelhof',
  'Toblerplatz',
  'Toni-Areal',
  'Trichtenhausenfussweg',
  'Trichtisal',
  'Triemli',
  'Triemlispital',
  'Tüffenwies',
  'Tulpenstrasse',
  'Tunnelstrasse',
  'Uetlihof',
  'Universität Irchel',
  'Unteraffoltern',
  'Untermoosstrasse',
  'Verenastrasse',
  'Vogelsangstrasse',
  'Voltastrasse',
  'Vulkanstrasse',
  'Waffenplatz-/Bederstr.',
  'Waffenplatzstrasse',
  'Waidbadstrasse',
  'Waidfussweg',
  'Waidhof',
  'Waidspital',
  'Waldgarten',
  'Waldhaus Dolder',
  'Wartau',
  'Waserstrasse',
  'Weihersteig',
  'Werd',
  'Werdhölzli',
  'Wetlistrasse',
  'Widmerstrasse',
  'Wieslergasse',
  'Wiesliacher',
  'Wildbachstrasse',
  'Winkelriedstrasse',
  'Winzerhalde',
  'Winzerstrasse',
  'Winzerstrasse Süd',
  'Wipkingerplatz',
  'Witikon Zentrum',
  'Wollishofen',
  'Wonnebergstrasse',
  'Würzgraben',
  'Zehntenhausplatz',
  'Zielweg',
  'Zoo',
  'Zoo/Forrenweid',
  'Zürich Affoltern',
  'Zürich Altstetten',
  'Zürich Balgrist',
  'Zürich Binz',
  'Zürich Brunau',
  'Zürich Enge',
  'Zürich Friesenberg',
  'Zürich Giesshübel',
  'Zürich Hardbrücke',
  'Zürich HB',
  'Zürich HB Museum',
  'Zürich HB Sihlpost',
  'Zürich HB SZU',
  'Zürich Hegibachplatz',
  'Zürich Kreuzplatz',
  'Zürich Leimbach',
  'Zürich Manegg',
  'Zürich Oerlikon',
  'Zürich Rehalp',
  'Zürich Saalsporthalle',
  'Zürich Schweighof',
  'Zürich Seebach',
  'Zürich Selnau',
  'Zürich Stadelhofen',
  'Zürich Tiefenbrunnen',
  'Zürich Triemli',
  'Zürich Wiedikon',
  'Zürich Wipkingen',
  'Zürich Wollishofen',
  'Zürichbergstrasse',
  'Zweiackerstrasse',
  'Zwielplatz',
  'Zwinglihaus',
  'Zypressenstrasse'
]
