create table "public"."mr_t_locations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text not null
);


alter table "public"."mr_t_locations" enable row level security;

CREATE UNIQUE INDEX mr_t_locations_pkey ON public.mr_t_locations USING btree (id);

alter table "public"."mr_t_locations" add constraint "mr_t_locations_pkey" PRIMARY KEY using index "mr_t_locations_pkey";


create policy "Enable full access for admins"
on "public"."mr_t_locations"
as permissive
for all
to authenticated
using ((role_for(auth.uid()) = 'admin'::text))
with check ((role_for(auth.uid()) = 'admin'::text));


create policy "Enable reading for operators"
on "public"."mr_t_locations"
as permissive
for select
to authenticated
using ((role_for(auth.uid()) = 'operator'::text));

