create table "public"."stations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text not null,
    "value" smallint not null
);

alter table "public"."stations" enable row level security;

CREATE UNIQUE INDEX stations_pkey ON public.stations USING btree (id);

alter table "public"."stations" add constraint "stations_pkey" PRIMARY KEY using index "stations_pkey";

create policy "Enable reading for authenticated users only"
on "public"."stations"
as permissive
for select
to authenticated
using (true);
